pub const SUCCESS: i16 = 0;

pub const SYSTEM_ERROR: i16 = 1;

pub const SYSTEM_BUSY: i16 = 2;

pub const REQUEST_CODE_NOT_SUPPORTED: i16 = 3;

pub const TRANSACTION_FAILED: i16 = 4;
pub const FLUSH_DISK_TIMEOUT: i16 = 10;

pub const SLAVE_NOT_AVAILABLE: i16 = 11;

pub const FLUSH_SLAVE_TIMEOUT: i16 = 12;

pub const MESSAGE_ILLEGAL: i16 = 13;

pub const SERVICE_NOT_AVAILABLE: i16 = 14;

pub const VERSION_NOT_SUPPORTED: i16 = 15;

pub const NO_PERMISSION: i16 = 16;

pub const TOPIC_NOT_EXIST: i16 = 17;
pub const TOPIC_EXIST_ALREADY: i16 = 18;
pub const PULL_NOT_FOUND: i16 = 19;

pub const PULL_RETRY_IMMEDIATELY: i16 = 20;

pub const PULL_OFFSET_MOVED: i16 = 21;

pub const QUERY_NOT_FOUND: i16 = 22;

pub const SUBSCRIPTION_PARSE_FAILED: i16 = 23;

pub const SUBSCRIPTION_NOT_EXIST: i16 = 24;

pub const SUBSCRIPTION_NOT_LATEST: i16 = 25;

pub const SUBSCRIPTION_GROUP_NOT_EXIST: i16 = 26;

pub const FILTER_DATA_NOT_EXIST: i16 = 27;

pub const FILTER_DATA_NOT_LATEST: i16 = 28;

pub const TRANSACTION_SHOULD_COMMIT: i16 = 200;

pub const TRANSACTION_SHOULD_ROLLBACK: i16 = 201;

pub const TRANSACTION_STATE_UNKNOWN: i16 = 202;

pub const TRANSACTION_STATE_GROUP_WRONG: i16 = 203;
pub const NO_BUYER_ID: i16 = 204;

pub const NOT_IN_CURRENT_UNIT: i16 = 205;

pub const CONSUMER_NOT_ONLINE: i16 = 206;

pub const CONSUME_MSG_TIMEOUT: i16 = 207;

pub const NO_MESSAGE: i16 = 208;
